refactor[janitor,mirtime,installpkg,upgrade,rewifi]!: Restructure 'janitor', rename 'mirlisttime' to 'mirtime', deprecate 'rewifi'.

diff --git a/janitor b/janitor
--- a/janitor
+++ b/janitor
@@ -1,66 +1,72 @@
 #!/bin/bash
 
-SCRIPTS_PATH=$(dirname "$(realpath "$0")")/utility_scripts
+#TODO: Make man page!
+help_string=$'
+\e[1;4mMaintenance and utility scripts\e[0m
 
-_help() {
-    echo
-    echo -e "\e[1mMaintenance and utility scripts.\e[0m"
-    echo
-    echo -e "\e[1mSynopsis:\e[0m janitor <operation> [options] [targets]"
-    echo
-    echo -e "\e[1mOperations:\e[0m"
-    echo -e "    \e[1m<no operation>, --greet\e[0m"
-    echo "        Display an informative greeting."
-    echo
-    echo -e "    \e[1m-u, --upgrade\e[0m <packages>"
-    echo "        Update and upgrade the system."
-    echo
-    echo -e "    \e[1m-i, --installpkg\e[0m <packages>"
-    echo "        Install packages."
-    echo
-    echo -e "    \e[1m-r, --removepkg\e[0m <packages>"
-    echo "        Remove packages."
-    echo
-    echo -e "    \e[1m-c, --clean\e[0m"
-    echo "        Clean up after pacman and paru."
-    echo
-    echo -e "    \e[1m-x, --expel\e[0m <paths>"
-    echo "        Move files and directories to trash."
-    echo
-    echo -e "    \e[1m--mpvwebcam\e[0m"
-    echo "        Display webcam output in mpv."
-    echo
-    echo -e "    \e[1m--rewifi\e[0m"
-    echo "        Reload wifi driver module."
-    echo
-    echo -e "    \e[1m--sysinfo\e[0m"
-    echo "        Display system information."
-    echo
-    echo -e "    \e[1m--mirlisttime\e[0m [options]"
-    echo "        Display when the current mirrorlist was retrieved."
-    echo
-    echo -e "            \e[1m-n\e[0m      Display an empty line before and after the message if there"
-    echo "                    is one."
-    echo
-    echo -e "    \e[1m--install\e[0m"
-    echo -e "        Create a symlink to this script called \e[3mjanitor\e[0m in /usr/local/bin."
-    echo
-    echo -e "    \e[1m--uninstall\e[0m"
-    echo -e "        Remove a symlink to this script called \e[3mjanitor\e[0m from /usr/local/bin."
-    echo
-    echo -e "    \e[1m--patches\e[0m"
-    echo -e "        List available patches."
-    echo
-    echo -e "    \e[1m--patch\e[0m <patches>"
-    echo -e "        Apply specified patches."
-    echo
-    echo -e "    \e[1m--unpatch\e[0m <patches>"
-    echo -e "        Remove specified patches."
-    echo
-    echo -e "    \e[1m-h, --help\e[0m"
-    echo "        Print this help."
-    echo
-}
+\e[1mSynopsis:\e[0m janitor <operation> [options] [targets]
+
+\e[1mSetup:\e[0m
+
+    \e[1m--install\e[0m
+        Create a symlink to this script called \e[3mjanitor\e[0m in /usr/local/bin.
+
+    \e[1m--uninstall\e[0m
+        Remove a symlink to this script called \e[3mjanitor\e[0m from /usr/local/bin.
+
+    \e[1m--patches\e[0m
+        List available patches.
+
+    \e[1m--patch\e[0m <patches>
+        Apply specified patches.
+
+    \e[1m--unpatch\e[0m <patches>
+        Remove specified patches.
+
+\e[1mMain operations:\e[0m
+
+    \e[1m<no operation>, --greet\e[0m
+        Display an informative greeting.
+
+    \e[1m-h, --help\e[0m
+        Display this help.
+
+    \e[1m-u, --upgrade\e[0m <package(s)>
+        Upgrade the system and optionally install packages.
+        This will upgrade official and AUR packages, and run pacdiff and clean
+        up afterwards.
+
+    \e[1m-i, --installpkg\e[0m <package(s)>
+        Install packages.
+
+    \e[1m-r, --removepkg\e[0m <package(s)>
+        Remove packages.
+
+    \e[1m-c, --clean\e[0m
+        Clean up after pacman and paru.
+
+    \e[1m-x, --expel\e[0m <paths>
+        Move files and directories to trash.
+
+    \e[1m--sysinfo\e[0m
+        Display system information.
+
+    \e[1m--mpvwebcam\e[0m
+        Display webcam output in mpv.
+
+    \e[1m--mirtime\e[0m [options]
+        Display when the current mirrorlist was retrieved.
+
+            \e[1m-n\e[0m      Display an empty line before and after the message, if there
+                    is one.
+
+\e[1mDeprecated:\e[0m
+
+    \e[1m--rewifi\e[0m
+        Reload wifi driver module.
+'
+
+scripts_path=$(dirname "$(realpath "$0")")/utility_scripts
 
 _install() {
     sudo ln -s "$(realpath "$0")" /usr/local/bin
@@ -70,64 +76,69 @@ _uninstall() {
     sudo unlink /usr/local/bin/janitor
 }
 
+_opt_error() {
+    echo -e "\e[91;1mError:\e[22m Invalid option $2-$1\e[0m"
+    echo "Try 'janitor --help' for more information."
+}
+
 if [ $# -eq 0 ]; then
-    "$SCRIPTS_PATH"/greet
+    "$scripts_path"/greet
     exit
 fi
 
 while getopts ":hcui:r:x:-:" opt; do
     case $opt in
-        h)  _help
+        h)  echo "$help_string"
             exit;;
-        c)  "$SCRIPTS_PATH"/clean
+        c)  "$scripts_path"/clean
             exit;;
-        u)  systemd-inhibit "$SCRIPTS_PATH"/upgrade "${@:2}"
+        u)  systemd-inhibit "$scripts_path"/upgrade "${@:2}"
             exit;;
-        i)  systemd-inhibit "$SCRIPTS_PATH"/installpkg "${@:2}"
+        i)  systemd-inhibit "$scripts_path"/installpkg "${@:2}"
             exit;;
-        r)  "$SCRIPTS_PATH"/removepkg "${@:2}"
+        r)  "$scripts_path"/removepkg "${@:2}"
             exit;;
-        x)  "$SCRIPTS_PATH"/expel "${@:2}"
+        x)  "$scripts_path"/expel "${@:2}"
             exit;;
         -)  case $OPTARG in
-                help)           _help
-                                exit;;
-                clean)          "$SCRIPTS_PATH"/clean
-                                exit;;
-                upgrade)        systemd-inhibit "$SCRIPTS_PATH"/upgrade "${@:2}"
-                                exit;;
-                installpkg)     systemd-inhibit "$SCRIPTS_PATH"/installpkg "${@:2}"
-                                exit;;
-                removepkg)      "$SCRIPTS_PATH"/removepkg "${@:2}"
-                                exit;;
-                expel)          "$SCRIPTS_PATH"/expel "${@:2}"
-                                exit;;
-                greet)          "$SCRIPTS_PATH"/greet
-                                exit;;
-                mpvwebcam)      "$SCRIPTS_PATH"/mpvwebcam
-                                exit;;
-                sysinfo)        "$SCRIPTS_PATH"/sysinfo
-                                exit;;
-                mirlisttime)    "$SCRIPTS_PATH"/mirlisttime $2
-                                exit;;
-                install)        _install
-                                exit;;
-                uninstall)      _uninstall
-                                exit;;
-                patches)        "$SCRIPTS_PATH"/patch list
-                                exit;;
-                patch)          "$SCRIPTS_PATH"/patch apply "${@:2}"
-                                exit;;
-                unpatch)        "$SCRIPTS_PATH"/patch remove "${@:2}"
-                                exit;;
-                rewifi)         "$SCRIPTS_PATH"/rewifi
-                                exit;;
-                *)              # Invalid option
-                                echo -e "\e[91;1mError:\e[22m Invalid option --$OPTARG\e[0m"
-                                exit 1;;
+                help)       echo "$help_string"
+                            exit;;
+                clean)      "$scripts_path"/clean
+                            exit;;
+                upgrade)    systemd-inhibit "$scripts_path"/upgrade "${@:2}"
+                            exit;;
+                installpkg) systemd-inhibit "$scripts_path"/installpkg "${@:2}"
+                            exit;;
+                removepkg)  "$scripts_path"/removepkg "${@:2}"
+                            exit;;
+                expel)      "$scripts_path"/expel "${@:2}"
+                            exit;;
+                greet)      "$scripts_path"/greet
+                            exit;;
+                mpvwebcam)  "$scripts_path"/mpvwebcam
+                            exit;;
+                sysinfo)    "$scripts_path"/sysinfo
+                            exit;;
+                mirtime)    "$scripts_path"/mirtime $2
+                            exit;;
+                install)    _install
+                            exit;;
+                uninstall)  _uninstall
+                            exit;;
+                patches)    "$scripts_path"/patch list
+                            exit;;
+                patch)      "$scripts_path"/patch apply "${@:2}"
+                            exit;;
+                unpatch)    "$scripts_path"/patch remove "${@:2}"
+                            exit;;
+                rewifi)     "$scripts_path"/rewifi
+                            exit;;
+                *)          # Invalid option
+                            _opt_error $OPTARG "-"
+                            exit 1;;
             esac;;
         \?) # Invalid option
-            echo -e "\e[91;1mError:\e[22m Invalid option -$OPTARG\e[0m"
+            _opt_error $OPTARG
             exit 1;;
     esac
 done
