refactor[janitor,README,utility_scripts]: Give several utility scripts more descriptive names.

diff --git a/janitor b/janitor
--- a/janitor
+++ b/janitor
@@ -9,23 +9,23 @@ _help() {
     echo -e "\e[1mSynopsis:\e[0m janitor <operation> [options] [target]"
     echo
     echo -e "\e[1mOperations:\e[0m"
-    echo -e "    \e[1m<no operation>, --hi\e[0m"
+    echo -e "    \e[1m<no operation>, --greet\e[0m"
     echo "        Display an informative greeting."
     echo
-    echo -e "    \e[1m-u, --up\e[0m"
+    echo -e "    \e[1m-u, --upgrade\e[0m"
     echo "        Update and upgrade the system."
     echo
-    echo -e "    \e[1m-i, --in\e[0m <package>"
+    echo -e "    \e[1m-i, --installpkg\e[0m <package>"
     echo "        Install a package."
     echo
-    echo -e "    \e[1m-o, --out\e[0m <package>"
+    echo -e "    \e[1m-r, --removepkg\e[0m <package>"
     echo "        Remove a package."
     echo
     echo -e "    \e[1m-c, --clean\e[0m"
     echo "        Clean up after pacman and paru."
     echo
-    echo -e "    \e[1m-r, --rm\e[0m <path>"
-    echo "        Remove a file or directory somewhat safely."
+    echo -e "    \e[1m-x, --expel\e[0m <path>"
+    echo "        Move a file or directory to trash."
     echo
     echo -e "    \e[1m--mpvwebcam\e[0m"
     echo "        Display webcam output in mpv."
@@ -71,7 +71,7 @@ _uninstall() {
 }
 
 if [ $# -eq 0 ]; then
-    "$SCRIPTS_PATH"/hi
+    "$SCRIPTS_PATH"/greet
     exit
 fi
 
@@ -81,50 +81,50 @@ while getopts ":hcui:o:r:-:" opt; do
             exit;;
         c)  "$SCRIPTS_PATH"/clean
             exit;;
-        u)  systemd-inhibit "$SCRIPTS_PATH"/up
+        u)  systemd-inhibit "$SCRIPTS_PATH"/upgrade
             exit;;
-        i)  systemd-inhibit "$SCRIPTS_PATH"/in "${@:2}"
+        i)  systemd-inhibit "$SCRIPTS_PATH"/installpkg "${@:2}"
             exit;;
-        o)  "$SCRIPTS_PATH"/out "${@:2}"
+        r)  "$SCRIPTS_PATH"/removepkg "${@:2}"
             exit;;
-        r)  "$SCRIPTS_PATH"/rm "${@:2}"
+        x)  "$SCRIPTS_PATH"/expel "${@:2}"
             exit;;
         -)  case $OPTARG in
-                help)       _help
-                            exit;;
-                clean)      "$SCRIPTS_PATH"/clean
-                            exit;;
-                up)         systemd-inhibit "$SCRIPTS_PATH"/up "${@:2}"
-                            exit;;
-                in)         systemd-inhibit "$SCRIPTS_PATH"/in "${@:2}"
-                            exit;;
-                out)        "$SCRIPTS_PATH"/out "${@:2}"
-                            exit;;
-                rm)         "$SCRIPTS_PATH"/rm "${@:2}"
-                            exit;;
-                hi)         "$SCRIPTS_PATH"/hi
-                            exit;;
-                mpvwebcam)  "$SCRIPTS_PATH"/mpvwebcam
-                            exit;;
-                sysinfo)    "$SCRIPTS_PATH"/sysinfo
-                            exit;;
+                help)           _help
+                                exit;;
+                clean)          "$SCRIPTS_PATH"/clean
+                                exit;;
+                upgrade)        systemd-inhibit "$SCRIPTS_PATH"/upgrade "${@:2}"
+                                exit;;
+                installpkg)     systemd-inhibit "$SCRIPTS_PATH"/installpkg "${@:2}"
+                                exit;;
+                removepkg)      "$SCRIPTS_PATH"/removepkg "${@:2}"
+                                exit;;
+                expel)          "$SCRIPTS_PATH"/expel "${@:2}"
+                                exit;;
+                greet)          "$SCRIPTS_PATH"/greet
+                                exit;;
+                mpvwebcam)      "$SCRIPTS_PATH"/mpvwebcam
+                                exit;;
+                sysinfo)        "$SCRIPTS_PATH"/sysinfo
+                                exit;;
                 mirlisttime)    "$SCRIPTS_PATH"/mirlisttime $2
-                            exit;;
-                install)    _install
-                            exit;;
-                uninstall)  _uninstall
-                            exit;;
-                patches)    "$SCRIPTS_PATH"/patch list
-                            exit;;
-                patch)      "$SCRIPTS_PATH"/patch apply "${@:2}"
-                            exit;;
-                unpatch)    "$SCRIPTS_PATH"/patch remove "${@:2}"
-                            exit;;
-                rewifi)     "$SCRIPTS_PATH"/rewifi
-                            exit;;
-                *)          # Invalid option
-                            echo -e "\e[91;1mError:\e[22m Invalid option --$OPTARG\e[0m"
-                            exit 1;;
+                                exit;;
+                install)        _install
+                                exit;;
+                uninstall)      _uninstall
+                                exit;;
+                patches)        "$SCRIPTS_PATH"/patch list
+                                exit;;
+                patch)          "$SCRIPTS_PATH"/patch apply "${@:2}"
+                                exit;;
+                unpatch)        "$SCRIPTS_PATH"/patch remove "${@:2}"
+                                exit;;
+                rewifi)         "$SCRIPTS_PATH"/rewifi
+                                exit;;
+                *)              # Invalid option
+                                echo -e "\e[91;1mError:\e[22m Invalid option --$OPTARG\e[0m"
+                                exit 1;;
             esac;;
         \?) # Invalid option
             echo -e "\e[91;1mError:\e[22m Invalid option -$OPTARG\e[0m"
